# Generated by Django 3.1.2 on 2020-12-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_listenlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenlater',
            name='video_id',
            field=models.IntegerField(),
        ),
    ]
